package com.example.localization

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String, val isRtl: Boolean) {
    ENGLISH("en", "English", "English", false),
    URDU("ur", "Urdu", "اردو", true),
    HINDI("hi", "Hindi", "हिंदी", false),
    ARABIC("ar", "Arabic", "العربية", true),
    SPANISH("es", "Spanish", "Español", false)
}

data class AppStrings(
    val appTitle: String,
    val shield: String,
    val vault: String,
    val tracking: String,
    val community: String,
    val settings: String,
    val armed: String,
    val disarmed: String,
    val armShield: String,
    val disarmShield: String,
    val motionDetection: String,
    val motionDesc: String,
    val pocketProtection: String,
    val pocketDesc: String,
    val chargerAlarm: String,
    val chargerDesc: String,
    val wrongPinTrap: String,
    val wrongPinDesc: String,
    val emergencyPanic: String,
    val emergencyPanicDesc: String,
    val registeredMobiles: String,
    val registerNewDevice: String,
    val maxDevicesNotice: String,
    val imeiLabel: String,
    val imeiHint: String,
    val brandModel: String,
    val statusSafe: String,
    val statusStolen: String,
    val statusReported: String,
    val liveCoordinates: String,
    val batteryStatus: String,
    val onlineStatus: String,
    val openGoogleMaps: String,
    val communityTheftRegistry: String,
    val searchImeiHint: String,
    val reportTheftButton: String,
    val intruderLogs: String,
    val wrongPinAttempts: String,
    val enterPinToDisarm: String,
    val wrongPinEntered: String,
    val pinCorrect: String,
    val policeFirNumber: String,
    val policeStation: String,
    val submitReport: String,
    val language: String,
    val darkMode: String,
    val emergencyContact: String,
    val alarmSound: String,
    val voiceWarning: String,
    val strobeLight: String
)

object LocalizationProvider {
    fun getStrings(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.ENGLISH -> AppStrings(
                appTitle = "Thief Hunter",
                shield = "Shield",
                vault = "Device Vault",
                tracking = "Live GPS",
                community = "Community",
                settings = "Settings",
                armed = "SHIELD ARMED",
                disarmed = "SHIELD DISARMED",
                armShield = "ARM SECURITY SHIELD",
                disarmShield = "DISARM (ENTER PIN)",
                motionDetection = "Motion Detection",
                motionDesc = "Triggers siren if phone is moved or picked up",
                pocketProtection = "Pocket Guard",
                pocketDesc = "Alarms if phone is removed from pocket or bag",
                chargerAlarm = "Charger Unplug Alert",
                chargerDesc = "Sounds high siren if charging cable is detached",
                wrongPinTrap = "Wrong PIN Intruder Trap",
                wrongPinDesc = "Snaps front camera selfie upon wrong PIN entry",
                emergencyPanic = "Emergency SOS Siren",
                emergencyPanicDesc = "Instantly blares 110dB police siren & strobe",
                registeredMobiles = "Registered Mobiles (Up to 10)",
                registerNewDevice = "Register New Device",
                maxDevicesNotice = "Maximum 10 devices registered in secure vault",
                imeiLabel = "IMEI Number",
                imeiHint = "Dial *#06# to obtain 15-digit IMEI",
                brandModel = "Brand & Model",
                statusSafe = "PROTECTED",
                statusStolen = "STOLEN / LOST",
                statusReported = "POLICE REPORTED",
                liveCoordinates = "Live GPS Telemetry",
                batteryStatus = "Battery & Health",
                onlineStatus = "Connection Status",
                openGoogleMaps = "View in Google Maps",
                communityTheftRegistry = "Public Stolen Registry",
                searchImeiHint = "Check IMEI before buying used phones...",
                reportTheftButton = "File Police Theft Report",
                intruderLogs = "Intruder Selfie Logs",
                wrongPinAttempts = "Unauthorized Access Attempts",
                enterPinToDisarm = "Enter 4-Digit Security PIN",
                wrongPinEntered = "Wrong PIN! Photo Captured & Alarm Triggered",
                pinCorrect = "PIN Verified. Shield Disarmed",
                policeFirNumber = "Police FIR / Crime Report #",
                policeStation = "Jurisdiction Police Station",
                submitReport = "Submit Theft Incident Report",
                language = "Application Language",
                darkMode = "Dark Display Theme",
                emergencyContact = "Emergency Alert Contact",
                alarmSound = "Audible Police Siren",
                voiceWarning = "Spoken Voice Warnings",
                strobeLight = "Emergency Screen Strobe"
            )
            AppLanguage.URDU -> AppStrings(
                appTitle = "تھیف ہنٹر",
                shield = "حفاظتی ڈھال",
                vault = "ڈیوائس والٹ",
                tracking = "لائیو جی پی ایس",
                community = "کمیونٹی",
                settings = "ترتیبات",
                armed = "حفاظت فعال ہے",
                disarmed = "حفاظت بند ہے",
                armShield = "حفاظتی شیلڈ فعال کریں",
                disarmShield = "شیلڈ غیر فعال کریں (پن درج کریں)",
                motionDetection = "حرکت کا الارم",
                motionDesc = "اگر فون ہلایا جائے تو الارم بجے گا",
                pocketProtection = "جیب سے نکالنے کا الارم",
                pocketDesc = "جیب سے فون نکلتے ہی زوردار آواز کرے گا",
                chargerAlarm = "چارجر اترنے کا الارم",
                chargerDesc = "چارجر ہٹانے پر ہنگامی سائرن بجائے گا",
                wrongPinTrap = "غلط پن کیمرہ ٹریپ",
                wrongPinDesc = "غلط پاس ورڈ پر چور کی سیلفی محفوظ ہوگی",
                emergencyPanic = "ہنگامی ایس او ایس سائرن",
                emergencyPanicDesc = "فوری طور پر اونچا سائرن اور فلیش لائٹ",
                registeredMobiles = "محفوظ موبائلز (زیادہ سے زیادہ 10)",
                registerNewDevice = "نیا موبائل رجسٹر کریں",
                maxDevicesNotice = "والٹ میں زیادہ سے زیادہ 10 موبائل محفوظ کیے جا سکتے ہیں",
                imeiLabel = "آئی ایم ای آئی نمبر",
                imeiHint = "اپنے فون پر *#06# ملا کر 15 ہندسوں کا IMEI لیں",
                brandModel = "برانڈ اور ماڈل",
                statusSafe = "محفوظ",
                statusStolen = "چوری شدہ",
                statusReported = "پولیس کو رپورٹ شدہ",
                liveCoordinates = "موجودہ جغرافیائی مقام",
                batteryStatus = "بیٹری کی حالت",
                onlineStatus = "انٹرنیٹ کنکشن",
                openGoogleMaps = "گوگل میپس پر دیکھیں",
                communityTheftRegistry = "عوامی چوری شدہ ڈیٹا بیس",
                searchImeiHint = "استعمال شدہ فون خریدنے سے پہلے IMEI چیک کریں...",
                reportTheftButton = "چوری کی رپورٹ درج کریں",
                intruderLogs = "چور کی سیلفی تصاویر",
                wrongPinAttempts = "غیر مجاز کوششیں",
                enterPinToDisarm = "4 ہندسوں کا سیکیورٹی پن درج کریں",
                wrongPinEntered = "غلط پن! تصویر محفوظ اور سائرن بج گیا",
                pinCorrect = "درست پن، شیلڈ بند ہو گئی",
                policeFirNumber = "پولیس ایف آئی آر نمبر",
                policeStation = "متعلقہ تھانہ",
                submitReport = "چوری کی رپورٹ جمع کروائیں",
                language = "ایپ کی زبان",
                darkMode = "ڈارک موڈ",
                emergencyContact = "ہنگامی رابطہ نمبر",
                alarmSound = "سائرن کی آواز",
                voiceWarning = "صوتی انتباہ",
                strobeLight = "اسکرین فلشنگ لائٹ"
            )
            AppLanguage.HINDI -> AppStrings(
                appTitle = "थीफ हंटर",
                shield = "सुरक्षा ढाल",
                vault = "डिवाइस वॉल्ट",
                tracking = "लाइव जीपीएस",
                community = "समुदाय",
                settings = "सेटिंग्स",
                armed = "सुरक्षा सक्रिय",
                disarmed = "सुरक्षा निष्क्रिय",
                armShield = "सुरक्षा सक्रिय करें",
                disarmShield = "निष्क्रिय करें (पिन डालें)",
                motionDetection = "मोशन डिटेक्शन अलार्म",
                motionDesc = "फोन हिलाने पर तुरंत सायरन बजेगा",
                pocketProtection = "पॉकेट सुरक्षा",
                pocketDesc = "जेब से निकालते ही अलार्म बजेगा",
                chargerAlarm = "चार्जर डिस्कनेक्ट अलार्म",
                chargerDesc = "चार्जर हटाने पर तेज आवाज करेगा",
                wrongPinTrap = "गलत पिन कैमरा ट्रैप",
                wrongPinDesc = "गलत पिन डालने पर घुसपैठिए की फोटो लेगा",
                emergencyPanic = "आपातकालीन पैनिक सायरन",
                emergencyPanicDesc = "तत्काल तेज पुलिस सायरन और फ्लैश लाइट",
                registeredMobiles = "पंजीकृत मोबाइल (अधिकतम 10)",
                registerNewDevice = "नया डिवाइस पंजीकृत करें",
                maxDevicesNotice = "वॉल्ट में अधिकतम 10 फोन जोड़े जा सकते हैं",
                imeiLabel = "आईएमईआई नंबर",
                imeiHint = "*#06# डायल करके 15 अंकों का IMEI प्राप्त करें",
                brandModel = "ब्रांड और मॉडल",
                statusSafe = "सुरक्षित",
                statusStolen = "चोरी हुआ",
                statusReported = "पुलिस में दर्ज",
                liveCoordinates = "लाइव लोकेशन निर्देशांक",
                batteryStatus = "बैटरी स्थिति",
                onlineStatus = "कनेक्शन स्थिति",
                openGoogleMaps = "गूगल मैप्स में देखें",
                communityTheftRegistry = "सार्वजनिक चोरी रजिस्टर",
                searchImeiHint = "पुराना फोन खरीदने से पहले IMEI जांचें...",
                reportTheftButton = "चोरी की रिपोर्ट दर्ज करें",
                intruderLogs = "घुसपैठिए की फोटो लॉग",
                wrongPinAttempts = "अनधिकृत प्रयास",
                enterPinToDisarm = "4 अंकों का सुरक्षा पिन डालें",
                wrongPinEntered = "गलत पिन! फोटो ली गई और अलार्म चालू",
                pinCorrect = "पिन सत्यापित, सुरक्षा निष्क्रिय",
                policeFirNumber = "पुलिस एफआईआर संख्या",
                policeStation = "संबंधित पुलिस स्टेशन",
                submitReport = "रिपोर्ट सबमिट करें",
                language = "एप्लिकेशन भाषा",
                darkMode = "डार्क मोड",
                emergencyContact = "आपातकालीन संपर्क",
                alarmSound = "सायरन ध्वनि",
                voiceWarning = "आवाज चेतावनी",
                strobeLight = "आपातकालीन स्ट्रोब लाइट"
            )
            AppLanguage.ARABIC -> AppStrings(
                appTitle = "صياد اللصوص",
                shield = "الدرع الأمني",
                vault = "خزينة الأجهزة",
                tracking = "التتبع المباشر",
                community = "المجتمع",
                settings = "الإعدادات",
                armed = "الحماية مفعلة",
                disarmed = "الحماية معطلة",
                armShield = "تفعيل درع الحماية",
                disarmShield = "تعطيل الحماية (أدخل الرمز)",
                motionDetection = "إنذار كشف الحركة",
                motionDesc = "ينطلق صفارة الإنذار إذا تم تحريك الهاتف",
                pocketProtection = "حماية الجيب والحقيبة",
                pocketDesc = "ينبه فور إخراج الهاتف من الجيب",
                chargerAlarm = "إنذار فصل الشاحن",
                chargerDesc = "إنذار فوري عند نزع كابل الشحن",
                wrongPinTrap = "فخ الرمز الخاطئ",
                wrongPinDesc = "التقاط صورة ذاتية فور إدخال رمز خاطئ",
                emergencyPanic = "صفارة طوارئ SOS",
                emergencyPanicDesc = "تشغيل صفارة شرطة قوية مع وميض الشاشة",
                registeredMobiles = "الهواتف المسجلة (حتى 10)",
                registerNewDevice = "تسجيل جهاز جديد",
                maxDevicesNotice = "الحد الأقصى 10 أجهزة في الخزينة الآمنة",
                imeiLabel = "رقم الـ IMEI",
                imeiHint = "اتصل على *#06# لمعرفة رقم IMEI",
                brandModel = "الشركة والطراز",
                statusSafe = "آمن ومحمي",
                statusStolen = "مسروق / مفقود",
                statusReported = "تم إبلاغ الشرطة",
                liveCoordinates = "إحداثيات الموقع المباشر",
                batteryStatus = "مستوى البطارية",
                onlineStatus = "حالة الاتصال",
                openGoogleMaps = "عرض في خرائط جوجل",
                communityTheftRegistry = "سجل الهواتف المسروقة العام",
                searchImeiHint = "تحقق من IMEI قبل شراء هاتف مستعمل...",
                reportTheftButton = "تقديم بلاغ سرقة رسمي",
                intruderLogs = "سجل صور المتسللين",
                wrongPinAttempts = "محاولات الدخول غير المصرح بها",
                enterPinToDisarm = "أدخل رمز الأمان المكون من 4 أرقام",
                wrongPinEntered = "رمز خاطئ! تم التقاط الصورة وتشغيل الإنذار",
                pinCorrect = "تم التحقق، تم إلغاء تفعيل الدرع",
                policeFirNumber = "رقم محضر الشرطة",
                policeStation = "مركز الشرطة المختص",
                submitReport = "إرسال البلاغ",
                language = "لغة التطبيق",
                darkMode = "الوضع الداكن",
                emergencyContact = "جهة اتصال الطوارئ",
                alarmSound = "صوت صفارة الإنذار",
                voiceWarning = "تنبيه صوتي متحدث",
                strobeLight = "وميض الشاشة التحذيري"
            )
            AppLanguage.SPANISH -> AppStrings(
                appTitle = "Thief Hunter",
                shield = "Escudo",
                vault = "Bóveda",
                tracking = "GPS en Vivo",
                community = "Comunidad",
                settings = "Ajustes",
                armed = "ESCUDO ARMADO",
                disarmed = "ESCUDO DESARMADO",
                armShield = "ACTIVAR ESCUDO DE SEGURIDAD",
                disarmShield = "DESARMAR (INGRESAR PIN)",
                motionDetection = "Detección de Movimiento",
                motionDesc = "Activa sirena si el teléfono es movido o levantado",
                pocketProtection = "Protección de Bolsillo",
                pocketDesc = "Alarma si sacan el teléfono de tu bolsillo o bolso",
                chargerAlarm = "Alerta de Desconexión de Cargador",
                chargerDesc = "Suena fuerte si desconectan el cable de carga",
                wrongPinTrap = "Trampa de PIN Incorrecto",
                wrongPinDesc = "Captura selfie del intruso tras PIN erróneo",
                emergencyPanic = "Sirena de Emergencia SOS",
                emergencyPanicDesc = "Activa inmediatamente sirena policial de 110dB y estrobo",
                registeredMobiles = "Móviles Registrados (Hasta 10)",
                registerNewDevice = "Registrar Nuevo Dispositivo",
                maxDevicesNotice = "Máximo de 10 dispositivos protegidos en la bóveda",
                imeiLabel = "Número IMEI",
                imeiHint = "Marca *#06# para obtener los 15 dígitos del IMEI",
                brandModel = "Marca y Modelo",
                statusSafe = "PROTEGIDO",
                statusStolen = "ROBADO / PERDIDO",
                statusReported = "DENUNCIADO A POLICÍA",
                liveCoordinates = "Telemetría GPS en Tiempo Real",
                batteryStatus = "Batería y Estado",
                onlineStatus = "Estado de Red",
                openGoogleMaps = "Abrir en Google Maps",
                communityTheftRegistry = "Registro Público de Celulares Robados",
                searchImeiHint = "Comprueba el IMEI antes de comprar un teléfono usado...",
                reportTheftButton = "Denunciar Robo de Dispositivo",
                intruderLogs = "Registro de Selfies de Intrusos",
                wrongPinAttempts = "Intentos de Acceso No Autorizados",
                enterPinToDisarm = "Ingresa PIN de Seguridad de 4 Dígitos",
                wrongPinEntered = "¡PIN Incorrecto! Foto Capturada y Alarma Activada",
                pinCorrect = "PIN Verificado. Escudo Desarmado",
                policeFirNumber = "Nº de Denuncia Policial / FIR",
                policeStation = "Comisaría / Estación Policial",
                submitReport = "Enviar Informe de Robo",
                language = "Idioma de la Aplicación",
                darkMode = "Modo Oscuro",
                emergencyContact = "Contacto de Emergencia",
                alarmSound = "Sirena Policial Audaz",
                voiceWarning = "Alertas de Voz Habladas",
                strobeLight = "Estrobo de Pantalla de Emergencia"
            )
        }
    }
}
